// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nrpajydxcpeiafkpoyoz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ycGFqeWR4Y3BlaWFma3BveW96Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY4MTI1MzksImV4cCI6MjA1MjM4ODUzOX0.X1lhg233j18TWx-a6EifSlTKIt-umn4SJ8UoRsB03Ms";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);