// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://llswqgpmjvxjdpmdnypq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxsc3dxZ3BtanZ4amRwbWRueXBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3MTk2MjksImV4cCI6MjA1NTI5NTYyOX0.cvX-MJEwdK9HV1rBaA61RgTBu-O7PIxEgNQWDRNBcIw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);